name: Test & Lint

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-go@f111f3307d8850f501ac8e361feca8890f8794c3 # v5.5.0
        with:
          go-version: "1.26"

      - name: Run tests
        run: go test -count=1 ./...

      - name: Run vet
        run: go vet ./...
